services:
  jobmanager:
    image: flink:1.19.1-java17
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///flink-checkpoints
    volumes:
      - flink-checkpoints:/flink-checkpoints

  taskmanager:
    image: flink:1.19.1-java17
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///flink-checkpoints
    volumes:
      - flink-checkpoints:/flink-checkpoints

volumes:
  flink-checkpoints: